### ISSUE TITLE
运行出现错误Error:Execution failed for task ':app:transformClassesWithDexForBaiduDebug'. > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

### ISSUE THREAD

**Issue by jinhuizxc** [Zweihui/Aurora#1]
下载你的项目，项目构建是成功的，但是运行时出现这个问题
Error:Execution failed for task ':app:transformClassesWithDexForBaiduDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
关于这个错误，楼主知道是什么造成的么？求解答。

**Comment by Zweihui** [comment]
猜测是引用的Bmob库有依赖冲突，你先更新一下最新的代码（Bmob库更新到3.5.8了），然后构建完后，在项目的External Libraries下查看Bmob-sdk-3.5.8，然后手动删除gson-2.6.2.jar、okio-1.12.0.jar、org.apache.http.legacy.jar这3个包，然后再试一下运行可以不

**Comment by ruanguihua** [comment]
Error:Execution failed for task ':app:transformClassesWithDexForBaiduDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

按上面的方法也不行啊

**Comment by jinhuizxc** [comment]
亲测楼主更新3.0的代码，可以正常运行安装！
