### ISSUE TITLE
运行时会有这个错误，但是不知道具体是哪里引用的2.2.4版本的gson

### ISSUE THREAD

**Issue by tmexcept** [Zweihui/Aurora#2]
![image](https://user-images.githubusercontent.com/10299901/34481335-90b99e42-efec-11e7-8d90-fd4e0b90ea4f.png)

![image](https://user-images.githubusercontent.com/10299901/34481326-831d6642-efec-11e7-8e40-39f92e774d6b.png)

**Comment by Zweihui** [comment]
试一下，构建完后，在项目的External Libraries下查看Bmob-sdk-3.5.8，然后手动删除gson-2.6.2.jar、okio-1.12.0.jar、org.apache.http.legacy.jar这3个包
