### ISSUE TITLE
app:transformClassesWithDexForBaiduDebug

### ISSUE THREAD

**Issue by ruanguihua** [Zweihui/Aurora#3]
Error:Execution failed for task ':app:transformClassesWithDexForBaiduDebug'.

com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

按上面的方法也不行啊

**Comment by Zweihui** [comment]
尝试一下最新的代码，已经适配AS3.0了
