### ISSUE TITLE
不知是否可以请教一个问题呢？

### ISSUE THREAD

**Issue by jinhuizxc** [Zweihui/Aurora#6]

**Comment by tmexcept** [comment]
……

**Comment by Zweihui** [comment]
什么问题？

**Comment by jinhuizxc** [comment]
全局路由器 此类由apt自动生成 */
public final class TRouter 这个路由怎么生成的？

**Comment by Zweihui** [comment]
在lib:apt下有一个RouterProcessor类，自动生成的主要逻辑都在这里。还有你可以去了解一下java APT。
